#!/usr/bin/python
import sys

def main(inp):
    buf = ""
    for i in range(0,len(inp),2):
            buf+=chr(int(inp[i:i+2],16))
    print buf

if __name__ == "__main__":
    main("".join(sys.argv[1:]))


