#!/usr/bin/env python2
# copy and paste `x/100gx $addr` output from gdb
# and then get a big number in different forms.
import sys


inp = ""
print "[^_^] hit ctrl-c when done w/input" 
while True:
    try:
        inp+=raw_input(">")
    except KeyboardInterrupt:
        break

b = inp.replace("\n"," ")
c = filter(None,b.split(" "))

print b
print c
num = long(0)
byteform = ""
for byte in c:
    if len(byte) > 4 and byte[4:6] == "0x":
        byte = byte[0:4]
    if len(byte) == 4:
        num = num << 8 
        num+=int(byte,16)
        byteform+="\\x%02X"%int(byte,16) 
          
        
print ""
print "0x%X"%num
print ""
print byteform
    
   
